# Generated by Django 5.0.14 on 2026-09-14 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField()),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('category', models.CharField(max_length=30)),
                ('difficulty_tier', models.CharField(max_length=20)),
                ('difficulty_weight', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('submission_type', models.CharField(max_length=20)),
                ('evaluation_criteria', models.JSONField(default=dict)),
                ('benchmark_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('benchmark_unit', models.CharField(blank=True, max_length=40, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('requires_verification', models.BooleanField(default=True)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('challenges_joined', models.PositiveIntegerField(default=0)),
                ('challenges_completed', models.PositiveIntegerField(default=0)),
                ('challenges_in_progress', models.PositiveIntegerField(default=0)),
                ('challenges_failed', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('consistency_streak', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('status', models.CharField(default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('submission_payload', models.JSONField(default=dict)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('raw_performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(db_column='challenge_id', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.challenge')),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='ScoreAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_final_score', models.DecimalField(decimal_places=3, max_digits=9)),
                ('performance_normalized', models.DecimalField(decimal_places=3, max_digits=6)),
                ('difficulty_weight', models.DecimalField(decimal_places=3, max_digits=4)),
                ('completion_factor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('verification_factor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('consistency_bonus', models.DecimalField(decimal_places=3, max_digits=6)),
                ('community_signal_capped', models.DecimalField(decimal_places=3, max_digits=6)),
                ('breakdown', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.PROTECT, related_name='score_audits', to='challenges.submission')),
            ],
            options={
                'db_table': 'score_audit_log',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_id', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='challenges.submission')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='challenges.submission')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='challenges.submission')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user_id', 'challenge'), name='participants_user_challenge_unique'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user_id', 'challenge'), name='submissions_user_challenge_unique'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter_id', 'submission'), name='reports_reporter_submission_unique'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter_id', 'submission'), name='votes_voter_submission_unique'),
        ),
    ]
