# Generated by Django 5.2.17 on 2026-09-14 17:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=60)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_flags', to='challenges.submission')),
            ],
            options={
                'db_table': 'anomaly_flags',
                'indexes': [models.Index(fields=['status', 'created_at'], name='anomaly_fla_status_0f80a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='challenges.submission')),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_event_event_t_a71bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='challenges.submission')),
            ],
            options={
                'db_table': 'review_assignments',
                'constraints': [models.UniqueConstraint(fields=('submission', 'reviewer_id'), name='review_assignments_submission_reviewer_unique')],
            },
        ),
    ]
