# Generated by Django 5.2.17 on 2026-09-14 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_anomalyflag_auditevent_reviewassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='challenges.submission')),
            ],
            options={
                'db_table': 'votes',
                'constraints': [models.UniqueConstraint(fields=('voter_id', 'submission'), name='votes_voter_submission_unique')],
            },
        ),
    ]
